#!/usr/bin/ruby
def LoadListFile(file)
    ary = Array.new
    open(file, "r") do |fh|
	fh.each do |line|
	    line.chop!
	    next if (line =~ /^#/ || line =~ /^\s*$/)

	    ary.push(line)
	end
    end
    return ary
end

# Start from here...
scriptdir = File.expand_path(File.dirname($0)) + "/script"
$LOAD_PATH.push(scriptdir + "/lib")
#require "optparse"

if (ARGV.size < 1)
    STDERR.puts "usage: #{$0} <command>"
    exit 1
end

cmd = ARGV.shift


dirlist = LoadListFile("dirlist")

dirlist.each do |dir|
    puts "----------- START : #{cmd} in #{dir} -------------"
    cmdline = "(cd #{dir} && #{scriptdir}/mkpkg #{cmd})"
    puts cmdline
    if (!system(cmdline))
	puts "Abort."
	break
    end
    puts "----------- END : #{cmd} in #{dir} -------------"
    puts
end

puts "done."
