XMLFILE		= $(DOCNAME).xml
#XSLFILE		= ../xsl/docbook-xsl-1.66.1/html/tldp-one-page.xsl
XSLFILE		= ../xsl/main-html.xsl

all:	html

html: $(XMLFILE)
	xmlto html -x $(XSLFILE) -o $(DOCNAME) $(XMLFILE)
#	xsltproc -o test.html $(XSLFILE) $(XMLFILE)
	mkdir -p $(DOCNAME)/images
	cp ../images/*.png $(DOCNAME)/images
	cp ../css/xqt.css $(DOCNAME)

pdf: $(XMLFILE_UTF8)
	xmlto pdf -x ../xsl/main-pdf.xsl $(XMLFILE)

clean:
	-/bin/rm -rf *.html *.pdf $(DOCNAME)
